language: "en"

messages:
  en:
    damage_receive: " receives "
    damage: " damage. "
    damage_reason: "Reason: "

    death.attack.fall: "fall damage"
    death.attack.lava: "lava"
    death.attack.inFire: "fire"
    death.attack.drown: "drowning"
    death.attack.starve: "starvation"
    death.attack.outOfWorld: "the void"
    death.attack.freeze: "freezing"
    death.attack.magic: "magic"
    death.attack.cramming: "cramming"
    death.attack.wither: "wither"
    death.attack.inWall: "suffocation"
    death.attack.contact: "took contact damage"
    unknown-source: "unknown source"

  ru:
    damage_receive: " получает "
    damage: " урона. "
    damage_reason: "Причина: "

    death.attack.fall: "урон от падения"
    death.attack.lava: "лава"
    death.attack.inFire: "огонь"
    death.attack.drown: "утопление"
    death.attack.starve: "голод"
    death.attack.outOfWorld: "бездна"
    death.attack.freeze: "замерзание"
    death.attack.magic: "магия"
    death.attack.cramming: "давка"
    death.attack.wither: "иссушение"
    death.attack.inWall: "удушье"
    death.attack.contact: "укололся"
    unknown-source: "неизвестный источник"

  uk:
    damage_receive: " отримує "
    damage: " шкоди. "
    damage_reason: "Причина: "

    death.attack.fall: "урон від падіння"
    death.attack.lava: "лава"
    death.attack.inFire: "вогонь"
    death.attack.drown: "утоплення"
    death.attack.starve: "голод"
    death.attack.outOfWorld: "безодня"
    death.attack.freeze: "замерзання"
    death.attack.magic: "магія"
    death.attack.cramming: "тиснява"
    death.attack.wither: "висушення"
    death.attack.inWall: "задуха"
    death.attack.contact: "уколовся"
    unknown-source: "невідоме джерело"